CREATE TABLE IF NOT EXISTS "job" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp,
	"tags" text[],
	"company" text NOT NULL,
	"company_website" text,
	"location" text NOT NULL,
	"is_remote" boolean DEFAULT false NOT NULL,
	"salary_min" integer,
	"salary_max" integer,
	"currency" text,
	"job_type" text NOT NULL,
	"experience_level" text NOT NULL,
	"education_level" text,
	"required_skills" text[] NOT NULL,
	"preferred_skills" text[],
	"application_url" text,
	"contact_email" text,
	"is_active" boolean DEFAULT true NOT NULL
);
