export function getPopularCurrencies(): { value: string; name: string }[] {
  return [
    { value: "USD", name: "United States Dollar" },
    { value: "EUR", name: "Euro" },
    { value: "JPY", name: "Japanese Yen" },
    { value: "GBP", name: "British Pound Sterling" },
    { value: "AUD", name: "Australian Dollar" },
    { value: "CAD", name: "Canadian Dollar" },
    { value: "CHF", name: "Swiss Franc" },
    { value: "CNY", name: "Chinese Yuan" },
    { value: "SEK", name: "Swedish Krona" },
    { value: "NZD", name: "New Zealand Dollar" },
    { value: "MXN", name: "Mexican Peso" },
    { value: "SGD", name: "Singapore Dollar" },
    { value: "HKD", name: "Hong Kong Dollar" },
    { value: "NOK", name: "Norwegian Krone" },
    { value: "KRW", name: "South Korean Won" },
    { value: "TRY", name: "Turkish Lira" },
    { value: "INR", name: "Indian Rupee" },
    { value: "BRL", name: "Brazilian Real" },
    { value: "ZAR", name: "South African Rand" },
    { value: "RUB", name: "Russian Ruble" },
    { value: "BGN", name: "Bulgarian Lev" },
    { value: "RON", name: "Romanian Leu" },
    { value: "HRK", name: "Croatian Kuna" },
    { value: "CZK", name: "Czech Koruna" },
    { value: "DKK", name: "Danish Krone" },
    { value: "HUF", name: "Hungarian Forint" },
    { value: "PLN", name: "Polish Zloty" },
    { value: "SEK", name: "Swedish Krona" },
    { value: "NOK", name: "Norwegian Krone" },
  ];
}
